# =============================================================================
# Build, Scan, Sign & Publish AI-Box Images
# =============================================================================
# Triggered on push to main (when image-related files change) or manually.
# Builds all image variants with Buildah, pushes to Harbor, signs with Cosign,
# and scans with Trivy. Critical CVEs block the pipeline.
# =============================================================================

name: "Build, Scan, Sign & Publish AI-Box Images"

on:
  push:
    branches: [main]
    paths:
      - "base/**"
      - "java/**"
      - "node/**"
      - "dotnet/**"
      - "full/**"
      - "scripts/**"
  workflow_dispatch:
    inputs:
      image_variant:
        description: "Build a single variant instead of all (base, java, node, dotnet, full)"
        required: false
        type: choice
        options:
          - all
          - base
          - java
          - node
          - dotnet
          - full
        default: all

env:
  HARBOR_URL: ${{ secrets.HARBOR_URL }}
  HARBOR_USER: ${{ secrets.HARBOR_USER }}
  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
  COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
  REGISTRY: harbor.internal/aibox
  BASE_TAG: "24.04"
  DATE_TAG: "24.04-${{ github.run_id }}"

jobs:
  # ---------------------------------------------------------------------------
  # Job 1: Lint all Containerfiles with hadolint
  # ---------------------------------------------------------------------------
  lint:
    name: Lint Containerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run hadolint
        run: |
          chmod +x scripts/lint.sh
          ./scripts/lint.sh

  # ---------------------------------------------------------------------------
  # Job 2: Build base image (must complete before variants)
  # ---------------------------------------------------------------------------
  build-base:
    name: "Build base"
    needs: [lint]
    if: >-
      github.event_name != 'workflow_dispatch' ||
      github.event.inputs.image_variant == 'all' ||
      github.event.inputs.image_variant == 'base'
    runs-on: ubuntu-latest
    outputs:
      date_tag: ${{ steps.tags.outputs.date_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Buildah
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq buildah

      - name: Compute tags
        id: tags
        run: |
          DATE_TAG="24.04-$(date +%Y%m%d)"
          echo "date_tag=${DATE_TAG}" >> "$GITHUB_OUTPUT"
          echo "stable_tag=24.04" >> "$GITHUB_OUTPUT"

      - name: Log in to Harbor
        run: |
          buildah login \
            --username "${HARBOR_USER}" \
            --password "${HARBOR_PASSWORD}" \
            "${HARBOR_URL}"

      - name: Build base image
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh base "${{ steps.tags.outputs.stable_tag }}" "${REGISTRY}"
        env:
          DATE_TAG: ${{ steps.tags.outputs.date_tag }}

      - name: Sign base image
        run: |
          chmod +x scripts/sign.sh
          ./scripts/sign.sh "${REGISTRY}/base:${{ steps.tags.outputs.stable_tag }}"
          ./scripts/sign.sh "${REGISTRY}/base:${{ steps.tags.outputs.date_tag }}"

      - name: Scan base image
        run: |
          chmod +x scripts/scan-check.sh
          ./scripts/scan-check.sh "${REGISTRY}/base:${{ steps.tags.outputs.stable_tag }}"

  # ---------------------------------------------------------------------------
  # Job 3: Build variant images (depend on base)
  # ---------------------------------------------------------------------------
  build-variants:
    name: "Build ${{ matrix.variant }}"
    needs: [lint, build-base]
    if: >-
      github.event_name != 'workflow_dispatch' ||
      github.event.inputs.image_variant == 'all' ||
      github.event.inputs.image_variant == matrix.variant
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [java, node, dotnet, full]
        include:
          - variant: java
            stable_tag: "21-24.04"
          - variant: node
            stable_tag: "20-24.04"
          - variant: dotnet
            stable_tag: "8-24.04"
          - variant: full
            stable_tag: "24.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Buildah
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq buildah

      - name: Compute date tag
        id: tags
        run: |
          DATE_TAG="${{ matrix.stable_tag }}-$(date +%Y%m%d)"
          echo "date_tag=${DATE_TAG}" >> "$GITHUB_OUTPUT"

      - name: Log in to Harbor
        run: |
          buildah login \
            --username "${HARBOR_USER}" \
            --password "${HARBOR_PASSWORD}" \
            "${HARBOR_URL}"

      - name: Build variant image
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh "${{ matrix.variant }}" "${{ matrix.stable_tag }}" "${REGISTRY}"
        env:
          DATE_TAG: ${{ steps.tags.outputs.date_tag }}

      - name: Sign variant image
        run: |
          chmod +x scripts/sign.sh
          ./scripts/sign.sh "${REGISTRY}/${{ matrix.variant }}:${{ matrix.stable_tag }}"
          ./scripts/sign.sh "${REGISTRY}/${{ matrix.variant }}:${{ steps.tags.outputs.date_tag }}"

      - name: Scan variant image
        run: |
          chmod +x scripts/scan-check.sh
          ./scripts/scan-check.sh "${REGISTRY}/${{ matrix.variant }}:${{ matrix.stable_tag }}"
